### ISSUE TITLE
GitHub登録時の権限が大きすぎる？

### ISSUE THREAD

**Issue by dninomiya** [arcam-inc/gitwork-community#1]
<img width="563" alt="image" src="https://github.com/arcam-inc/gitwork-community/assets/5842851/6a66182c-78a8-4737-abbb-843b8160606f">

確かVercelなどは登録時にアクセスを許可するリポジトリを選択するスタイルだったと思うのですが、Gitworkの場合フル権限許可する印象がああり（違ったらすいません！）、クライアントワークを複数管理するGitHubアカウントで登録するときに結構気になりました。

理想としては指定したリポジトリの read, write(issueなど最低限）の権限に絞られていると嬉しいです。

現状の権限で個人のプライベートリポジトリをlistしたりdeleteできなければ問題ないと思うので、その旨登録時にワンクッション案内があると安心だと感じました。

**Comment by yuwzy** [comment]
@dninomiya 
権限の範囲を「Organization and teams」でRead-only access（プロジェクトを作成する際にOrganizationを選択するため）と「Personal user data」でEmail addressのread-only(メールアドレスを取得するため), profile informationのread-only(プロフィール情報を取得するため)に限定しました。
GitWork上からユーザーの招待やチーム設定の変更などを管理できるようのする場合は権限の範囲を変更する可能性はあります。
<img width="515" alt="スクリーンショット 2024-03-16 10 41 21" src="https://github.com/arcam-inc/gitwork-community/assets/10250246/bcb9226d-abd8-4db9-9bc9-f9edb6adc8e9">

**Comment by dninomiya** [comment]
@uedayuji 
LGTM!
