### ISSUE TITLE
アクティビティをお知らせと同じようにリッチにする

### ISSUE THREAD

**Issue by yuwzy** [arcam-inc/gitwork-community#16]
## 概要
プロジェクトの「アクティビティ」タブにプロジェクトでおこなわれたアクティビティを表示したい。

### アクティビティのタイプ

以下の通り、プロジェクトで行動がおこなわれたらアクティビティに行動のログが表示されること。

💻：タスク関連のアクティビティ
${管理者ユーザー名}さんが「${タスク名}」を作成しました。
${管理者ユーザー名}さんが「${タスク名}」を更新しました。
${管理者ユーザー名}さんが「${タスク名}」のフェーズを変更しました。
${管理者ユーザー名}さんが「${タスク名}」を完了にしました。
${管理者ユーザー名}さんが「${タスク名}」のアサインを変更しました。

👷：タスク候補者関連のアクティビティ
${ワーカーユーザー名}さんが「${タスク名}」に立候補しました。

👥：プロジェクトユーザー関連のアクティビティ
${ワーカーユーザー名}さんが招待を承諾しました。
${ワーカーユーザー名}さんが参加申請をしました。
${管理者ユーザー名}さんが${ワーカーユーザー名}さんの参加を承諾しました。

💯：プロジェクト評価関連のアクティビティ
${ワーカーユーザー名}さんが「${タスク名}」の評価を登録しました

📄：契約書関連のアクティビティ
${管理者ユーザー名}さんが「${契約書名}」を公開しました。
${管理者ユーザー名}さんが「${契約書名}」を非公開にしました。

### UIについて

UIは「お知らせ」と同じリストで表現されていること。

![Image](https://github.com/arcam-inc/gitwork-community/assets/10250246/9ec16230-6c44-444e-a3a9-9068e2387d47)

**Comment by daisukeiizuka** [comment]
@uedayuji 
現状の実装だと`ActivityService`が`ProjectUserService`に依存しているので、`ProjectUserService`から`ActivityService`を利用できない問題がありますね（プロジェクトユーザー関連のアクティビティが登録できない）

こちらについては、`CheckPrivilege`を`ProjectUserService`から切り出して`ActivityService`が`ProjectUserService`に依存しないように改修しようと思っているのですが、`CheckPrivilege`は参照箇所が多いので、改修範囲は結構広くなりそうです。
もし問題ありそうだったら連絡ください。

**Comment by yuwzy** [comment]
@daisukeiizuka 
ご連絡ありがとうございます、ご状況承知しました。
お手間ですが、そちらの対応で問題ございませんm(_ _)m
