### ISSUE TITLE
プロジェクト詳細（評価一覧）：非公開プロジェクトの場合は参画しておらず招待されてもいない場合、評価一覧画面にはそもそもアクセスできない。

### ISSUE THREAD

**Issue by yuwzy** [arcam-inc/gitwork-community#24]
# 背景
プロジェクトの評価一覧を表示する際、現在プロジェクトに参画及び招待されていない場合でもプロジェクトの評価一覧の画面にアクセス可能になっている。

# DoD
プロジェクト詳細の評価一覧について、
プロジェクト詳細（評価一覧）：非公開プロジェクトの場合は参画しておらず招待されてもいない場合、評価一覧画面にはそもそもアクセスできないようにする。タブもそもそも表示しないようにする。

**Comment by daisukeiizuka** [comment]
@uedayuji 
既にアクセスできないようになっているようです。
プロジェクト詳細自体を表示できないですし、レビュー一覧のURLを直リンクしてもエラーになります。
http://localhost:3000/projects/{projectID}/review
![Image](https://github.com/user-attachments/assets/9ef9500b-2cca-4a4b-acbb-92cbae1f1b9a)

**Comment by yuwzy** [comment]
ご確認ありがとうございます、Closeしてしまいます。
