### ISSUE TITLE
GitHub認証を登録時キャンセルすると404になる

### ISSUE THREAD

**Issue by dninomiya** [arcam-inc/gitwork-community#3]
ルートに戻ると良いかもです

**Comment by yuwzy** [comment]
@dninomiya 
![screencapture-localhost-3000-errors-error-2024-03-16-19_11_14](https://github.com/arcam-inc/gitwork-community/assets/10250246/31f10f0c-b75c-44f9-9289-34867363d5cb)
コールバック後にエラー画面に遷移して、具体的な操作手順を表示するようにしました。
※キャプチャはローカル環境でのキャプチャ

**Comment by dninomiya** [comment]
LGTM!
