### ISSUE TITLE
空状態でタスク、プロジェクト検索すると null が fill される

### ISSUE THREAD

**Issue by dninomiya** [arcam-inc/gitwork-community#32]
<img width="534" alt="image" src="https://github.com/user-attachments/assets/22879322-5ff6-4bce-96f9-e717161ba4fa">

- プロジェクト、タスク検索

**Comment by yuwzy** [comment]
@dninomiya 
こちら対応しました！各ページで同様の事象が発生していたので、そちらも解消しています。
問題なさそうでしたら、クローズでお願いします。

**Comment by dninomiya** [comment]
👍
