### ISSUE TITLE
オンボーディングフローがあると認知負荷が下がりそう

### ISSUE THREAD

**Issue by dninomiya** [arcam-inc/gitwork-community#33]
登録後いきなりダッシュボードが開くと圧倒されるので、たとえば以下のようなオンボーディングフローを経てメイン画面に移行すると認知コストが低く利用開始できるかもしれません

1. 目的は？（仕事を発注したい、受けたい）
2. 上記に応じたアクション
3. 注意点やコツ、困ったときの解決窓口などの表示
4. メイン画面に移行

*私はβ時期から登録していたので、現在はオンボーディングフローが実装されていることに気づけてない可能性あり*

その他認知負荷に関して気になった点を、新鮮なタイミングでコメントさせていただきます。

**Comment by dninomiya** [comment]
管理者だと抽象度が高くワーカーサイドではないことの理解がおいつかたなかったので「発注者」のようにより役割が明確なラベルの方が良いかもしれません（クラウドワークス系はそうなっていた記憶

<img width="268" alt="image" src="https://github.com/user-attachments/assets/98af0205-6d3c-4022-a9ed-ee12d33f3b29">

**Comment by dninomiya** [comment]
前提理解がズレてるかもですが、ワーカーモードとして使っている時に「プロジェクト作成」が行える状況に違和感を感じました。これは僕が発注者としての側面も持つからでしょうか

<img width="1428" alt="image" src="https://github.com/user-attachments/assets/3cb1ba6b-1db3-42f4-a6c1-e3d964ffb7da">

**Comment by dninomiya** [comment]
規約の量、厳格さ的な指標があっていいかもです。ワーカー目線だとローカルルールが巨大かつ厳守必須だと稼働負荷変わってくるため知っておきたい。発注者としては厳格な環境にラフなワーカーのコードを混ぜたくないなどもあるかも。

<img width="943" alt="image" src="https://github.com/user-attachments/assets/faa47b81-0cb9-4a23-b0dd-7b06afce6c88">

追記：概要欄でカバーすればいいからこちらではなくてもいい気がしてきました

**Comment by dninomiya** [comment]
こちらは自組織内のみ発注対象とするニュアンスでしょうか 👀 

<img width="792" alt="image" src="https://github.com/user-attachments/assets/1edd0baf-343f-468f-8d8f-cbe5014aed73">

**Comment by dninomiya** [comment]
立候補する前段階でコメントができると嬉しい。概要からは作業量が把握できないケースがありそうなので立候補前にクリアにできると安心して進める印象があります。

また、立候補後に後戻りできずにアサインされうるのか、が立候補時点で見えないので立候補後の流れがどこかでわかると安心して立候補できそうです。

立候補＝就活でいう応募になるのか、あるいはとりあえず話を聞くフェーズを指すのかが見えないイメージです。

**Comment by dninomiya** [comment]
今存在するタスクの場合、作業者目線だとツリーの情報があると嬉しいと感じました。

https://gitwork.jp/tasks/01J9D4YSKY20YP592D2H969NG8/overview

不要になったコードの精査、削除や汎用コンポーネントを使う上でツリーがかなり混沌として負債だらけある場合、リーディング負荷や影響範囲の予測困難性が懸念されるので事前にツリーがわかればそのあたりが見えるので嬉しい。

**Comment by dninomiya** [comment]
アサイン後の流れに付随しますが、アサイン後に想定外の要因（後出しや要件や条件など）により作業が膨れた場合などの交渉余地、フローが事前にどこかで見えると安心だと感じました。ヘルプや補足欄でそれが可能である旨を明記するなど。

**Comment by yuwzy** [comment]
@dninomiya 
こちら諸々対応いたしました！

### 対応した内容
 - オンボーディングフローの追加
 - 「管理者」から「発注者」へ変更
 - 「アサイン後に想定外の要因（後出しや要件や条件など）により作業が膨れた場合などの交渉余地、フロー」こちらは価格交渉のフローを新設しようと思います、ひとまずIssueを作成しました。(https://github.com/arcam-inc/gitwork-community/issues/40)

### その他補足
 - 「規約の量、厳格さ的な指標」は一旦プロジェクトの概要でカバーいただくようにします
 - 「権限を持っているユーザーにのみプロジェクトを表示する」は仰るとおり、自組織内のみ発注対象にする機能です。（プロジェクトやタスクの閲覧すらも防ぐ）
 - 「立候補する前段階でコメントができると嬉しい。」こちらはタスクコメントでコメント可能です。
 
 ### ご質問
> 今存在するタスクの場合、作業者目線だとツリーの情報があると嬉しいと感じました。
こちらがいまいち理解できず、ツリーはどのようなものを想定されていますでしょうか？？

お手すきでご確認お願いいたしますm(_ _)m

**Comment by dninomiya** [comment]
@uedayuji 
早速ありがとうございます！

ツリー＝ソースツリーになります。リファクタや不要ファイルの精査が要件にある場合、ソースツリーのカオスさで負荷が変わる的な背景。

こちらはツールというより発注者が概要欄でカバーする項目な気もするので、発注者向けのガイドラインで発注リテラシーをあげる施策があると良いかもですね 👀 

契約 fix するまでにコメントでリレー可能なようなのでそこで個別に解決できるので特段対応が不要かもしれません。

**Comment by dninomiya** [comment]
オンボーディングフローかなりいいですね！ ⭐

**Comment by yuwzy** [comment]
@dninomiya 
なるほどですね！
概要欄でのカバーや他のエンジニアからの評価で判断する形でどうかなと思っていました。
プロジェクトに参画 → タスク立候補 or アサイン という流れになるので、あまりにひどければ、コード見てからタスクを受けないという判断は開発者側で可能ですが。（双方あまり幸せではないですが...）
ワーカーに向けてプロジェクトの透明性をどのように担保するのかというのはもう少し深ぼって考えてみたいと思います。

> オンボーディングフローかなりいいですね！ ⭐

こちらありがとうございます、イメージと相違なくてよかったです！

**Comment by dninomiya** [comment]
LGTM!
