### ISSUE TITLE
アプリ内からサービスサイトへのリンクがあると嬉しい

### ISSUE THREAD

**Issue by dninomiya** [arcam-inc/gitwork-community#34]

**Comment by yuwzy** [comment]
@dninomiya 
こちらにホームのリンクを追加しました！お手すきでご確認お願いいたします。
<img width="265" alt="スクリーンショット 2024-10-13 14 23 05" src="https://github.com/user-attachments/assets/7a0b817a-9856-482b-b9c9-06050db849cc">

**Comment by dninomiya** [comment]
LGTM!
