### ISSUE TITLE
ログイン状態でLPに戻ると再ログインできる

### ISSUE THREAD

**Issue by dninomiya** [arcam-inc/gitwork-community#4]
こちらも未対応箇所かと思いますが、一応リストします!

(このレベルのフィードバック不要であれば言ってください！ 🙏 )

**Comment by yuwzy** [comment]
@dninomiya 
ダッシュボードに遷移した後ロゴをクリックすると、ダッシュボードのTop（現在は/projects）に遷移するように修正しました。
（gitwork.jp/に直接アクセスするとログインボタンが表示されるので再ログインも可能ですが、こちらは再ログインの挙動でよいかなと考えています。GitHubでログイン済みでgithub.co.jpに遷移した時と同じ挙動）

**Comment by dninomiya** [comment]
LGTM!
