### ISSUE TITLE
認証時に組織のgrantをつけないとプロジェクトを作れない？

### ISSUE THREAD

**Issue by dninomiya** [arcam-inc/gitwork-community#5]
<img width="425" alt="image" src="https://github.com/arcam-inc/gitwork-community/assets/5842851/188b4d89-b471-4a02-8f46-4892b5240247">

こちらの選択肢がなく、プロジェクト作成ができませんでした。認証時にorgのgrantつける必要あったかもです

**Comment by yuwzy** [comment]
@dninomiya 

登録時にGrantが付与されなかった場合に手動で設定する必要があります。
[ヘルプページ](https://github.com/arcam-inc/gitwork-community/wiki/%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E4%BD%9C%E6%88%90%E6%99%82%E3%81%AB%E3%82%AA%E3%83%BC%E3%82%AC%E3%83%8A%E3%82%A4%E3%82%BC%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%8C%E9%81%B8%E6%8A%9E%E3%81%A7%E3%81%8D%E3%81%AA%E3%81%84)を作成して、注釈を追記してみました。

<img width="1095" alt="スクリーンショット 2024-03-16 10 34 39" src="https://github.com/arcam-inc/gitwork-community/assets/10250246/5703a766-3648-4cab-ab13-8449b228060d">

**Comment by dninomiya** [comment]
🎉
