### ISSUE TITLE
ワーカーがタスクを作るシーンはありますか？

### ISSUE THREAD

**Issue by dninomiya** [arcam-inc/gitwork-community#6]
<img width="1440" alt="image" src="https://github.com/arcam-inc/gitwork-community/assets/5842851/387e8025-39d9-4915-b579-c63d2e44f559">

ワーカーも権限によってはタスクを作れる感じでしょうか？
この辺りのイメージが曖昧かもです

**Comment by yuwzy** [comment]
ユーザーがプロジェクトに所属する場合の権限は3つあって
 - オーナー
 - 管理者
 - メンバー
 なのですが、`オーナー`もしくは`管理者`で所属しているプロジェクトではタスクを作成することが可能です。
 `メンバー`権限で参加しているプロジェクトではタスクを作成することはできません。
 
ワーカー画面に切り替えている場合は「タスク作成」ボタンを表示しないように変更加えますね。

**Comment by dninomiya** [comment]
把握しました！
