### ISSUE TITLE
一覧から友達になる、をクリックするとエラートースト

### ISSUE THREAD

**Issue by dninomiya** [arcam-inc/gitwork-community#7]
**一覧から**　友達になる　をクリックで発生

<img width="1440" alt="image" src="https://github.com/arcam-inc/gitwork-community/assets/5842851/e551d00d-e7c2-40c1-9cdf-a40fad5c616c">

**Comment by yuwzy** [comment]
@dninomiya 
こちらリクエスト先のAPIの指定が誤っていました、修正して反映しています。
いただいていた友達申請をApproveする形で動作確認してしまいました。
（現在PCが故障中で、全体的に対応遅くなってます...mm）

**Comment by dninomiya** [comment]
LGTM!
